name: test

on: 
  workflow_dispatch

jobs:
  build-windows-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        run: |
          git clone https://github.com/google/angle .
      - name: Fetch depot_tools
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - name: Build
        shell: cmd
        run: |
          set PATH=%cd%\depot_tools;%PATH%
          set DEPOT_TOOLS_WIN_TOOLCHAIN=0
          set vs2019_install=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
          set WINDOWSSDKDIR=C:\Program Files (x86)\Windows Kits\10
          cmd /c gclient
          cmd /c python scripts/bootstrap.py
          cmd /c gclient sync
          cmd /c gn gen out/Release --args="is_debug=false target_cpu=\"x64\" build_angle_deqp_tests=false"
          cmd /c autoninja -C out/Release
      - name: Pack
        shell: bash
        run: |
          ls -al out/Release
          mkdir angle-windows-x64
          mkdir angle-windows-x64/dist
          rm -rf out/Release/gen
          rm -rf out/Release/obj
          mv -f out/Release/* angle-windows-x64/dist/
          cp -rf include angle-windows-x64/
          find angle-windows-x64 -name ".clang-format" -delete
          find angle-windows-x64 -name "*.md" -delete
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: angle-windows-x64
          path: angle-windows-x64
